# Default values for jobsite.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: nelrajan/jobsite
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: tagVersion

service:
  type: LoadBalancer
  port: 8000
