apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: {{ .Values.service.type}}
  selector:
    app: web
    type: front
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: 8000

